title = "Jordan Torbiak"
baseURL = "http://torbiak.com/"
googleAnalytics = "UA-97065292-1"
footnoteReturnLinkContents = "^"
[params]
  author = "Jordan Torbiak"
  description = "Articles and projects"
  card_image = "img/card.png"
